export class User {
	constructor(
		public _id: string,
		public name: string,
		public surname: string,
		public nick: string,
		public email: string,
		public password: string,
		public role: string,
		public image: string,
		public victorias: any,
		public derrotas: any,
		public reputation: string,
		public reputacionBeats: string,
		public reputacionBatallas: string,
		public reputacionFreestyle: string,
		public reputacionTemas: string,
		public totalBeats: string,
		public totalBatallas: string,
		public totalFreestyles: string,
		public totalTemas: string,
		public totalSeguidores:string,
		public totalSiguiendo:string,
		public portada: string,
		public fondo: string,
		public pais: string,
		public bio: string,
		public facebook: string,
		public youtube: string,
		public instagram: string,
		public twitter: string,
		public soundCloud: string,
		public web: string,
		public verificado: string,
		public ajustesChatPublico: string,
		public miniaturaBatalla: string,
		public textoComprarBeats: string,
		public enlaceComprarBeats: string,
		public textoMasInfo: string,
		public textoMasInfoProductor : string,
		public creado_el: string,
		public gettoken: any
	){}
}